version: 2.1
jobs:
  build:
    macos:
      xcode: "11.1.0"

    steps:
      - checkout

      - run:
          name: "Run Node SDK Demo"
          command: cd node && npm i && node src/index.js

      - run:
          name: "Run Swift SDK Demo"
          command: cd swift && carthage bootstrap && xcodebuild
