name: XpringSDKDemo
options:
  bundleIdPrefix: io.xpring
settings:
  LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks @loader_path/../Frameworks $(PROJECT_DIR)/Carthage/Build/..."
targets:
  Demo:
    type: tool
    platform: macOS
    sources: [Sources]
    dependencies:
      - carthage: XpringKit
      - carthage: SwiftProtobuf
      - carthage: SwiftGRPC

